// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInputDevices() {
  return window['go']['main']['App']['GetInputDevices']();
}

export function StartStream(arg1) {
  return window['go']['main']['App']['StartStream'](arg1);
}

export function StopStream() {
  return window['go']['main']['App']['StopStream']();
}
