// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {audio} from '../models';
import {main} from '../models';

export function GetInputDevices():Promise<Array<audio.Device>>;

export function StartStream(arg1:main.StreamParams):Promise<void>;

export function StopStream():Promise<void>;
